export default [
  { type: 'To Do', name: '#boston Myers + Chang - Cheap Date Night - Mons And Tues' },
  { type: 'To Do', name: '#cambridge H Mart' },
  { type: 'To Do', name: '#fly California' },
  { type: 'To Do', name: '#fly Iceland' },
  { type: 'To Do', name: '#fly Southeast Asia' },
  { type: 'To Do', name: '#fly Thailand' },
  { type: 'To Do', name: '#providence Dave And Busters' },
  { type: 'To Do', name: '#roadtrip Maryland' },
  { type: 'To Do', name: '#roadtrip Montreal' },
  { type: 'To Do', name: 'Aquarium http://www.eventkeeper.com/code/events.cfm?curorg=brookline' },
  { type: 'To Do', name: 'Arboretum' },
  { type: 'To Do', name: 'Bfresh' },
  { type: 'To Do', name: 'Bicycling' },
  { type: 'To Do', name: 'Blue Man Group Show' },
  { type: 'To Do', name: 'Bonsai Tree Class - http://www.bonsaiwest.com/index.php/bonsaiwest/courses#c1' },
  { type: 'To Do', name: 'Bruins Game' },
  { type: 'To Do', name: 'Chocolate / Cupcake & Dessert Tour' },
  { type: 'To Do', name: 'Cooking Classes https://www.eventbrite.com/o/the-kitchen-presented-by-the-trustees-1139069057' },
  { type: 'To Do', name: 'Florida' },
  { type: 'To Do', name: 'Fly Kites' },
  { type: 'To Do', name: 'Flying Trapeze Class' },
  { type: 'To Do', name: 'Foot Golf' },
  { type: 'To Do', name: 'Glass Blowing http://www.diabloglassschool.com/events.php' },
  { type: 'To Do', name: 'Go To A Ballet Show' },
  { type: 'To Do', name: 'Golden Temple E-room Dancing' },
  { type: 'To Do', name: 'Hot Air Balloon' },
  { type: 'To Do', name: 'Ice Skating In Boston Common' },
  { type: 'To Do', name: 'Lower Depths' },
  { type: 'To Do', name: 'Monday Night Trivia At Hops N Scotch' },
  { type: 'To Do', name: 'Paint Night' },
  { type: 'To Do', name: 'Plant Nite' },
  { type: 'To Do', name: 'Pottery Making Class' },
  { type: 'To Do', name: 'Pottery Wheel' },
  { type: 'To Do', name: 'Ramblewild' },
  { type: 'To Do', name: 'Rock Climbing' },
  { type: 'To Do', name: 'Rollerskating' },
  { type: 'To Do', name: 'Visit Primark' },
  { type: 'To Do', name: 'White Water Rafting' },
  { type: 'To Eat', name: '#allston Dim Sum Chef' },
  { type: 'To Eat', name: '#backbay Salty Pig' },
  { type: 'To Eat', name: '#brookline #brooklinevillage El Centro' },
  { type: 'To Eat', name: '#brookline #brooklinevillage Matt Murphys' },
  { type: 'To Eat', name: '#brookline Try Scotch Eggs At Hops And Scotch' },
  { type: 'To Eat', name: '#brookline Upper Crust - Avocado Pizza - https://instagram.com/p/3cvpv9lvji/' },
  { type: 'To Eat', name: '#brooklinevillage Baja Bettys Burritos' },
  { type: 'To Eat', name: '#brooklinevillage Bottega Di Capri' },
  { type: 'To Eat', name: '#brooklinevillage Clover - Sweet Potato Sandwich' },
  { type: 'To Eat', name: '#brooklinevillage Eat Family Restaurant' },
  { type: 'To Eat', name: '#brooklinevillage La Morra' },
  { type: 'To Eat', name: '#brooklinevillage Middle Gray' },
  { type: 'To Eat', name: '#brooklinevillage Oriental Pearl' },
  { type: 'To Eat', name: '#brooklinevillage Pinapple Thai' },
  { type: 'To Eat', name: '#brooklinevillage Pomodoro' },
  { type: 'To Eat', name: '#brooklinevillage Pon Thai Bistro' },
  { type: 'To Eat', name: '#brooklinevillage Village Pizza' },
  { type: 'To Eat', name: '#brooklinevillage Village Smokehouse' },
  { type: 'To Eat', name: '#brooklinevillage Virginia\'s Fine Foods' },
  { type: 'To Eat', name: '#brooklinevillage Yokohama' },
  { type: 'To Eat', name: '#cambridge Life Alive' },
  { type: 'To Eat', name: '#chestnuthill Pepe\'s Pizza' },
  { type: 'To Eat', name: '#chinatown Peach Farm - Salt Pep Squid' },
  { type: 'To Eat', name: '#coolidge Bottega Fiorentina' },
  { type: 'To Eat', name: '#coolidge Buffalo Shrimp At Hops Scotch' },
  { type: 'To Eat', name: '#coolidge Clear Flour Bread Macarons' },
  { type: 'To Eat', name: '#coolidge Corrib Pub' },
  { type: 'To Eat', name: '#coolidge Daily Catch' },
  { type: 'To Eat', name: '#coolidge Grainne O\'malley\'s' },
  { type: 'To Eat', name: '#coolidge Jerusalem Pita' },
  { type: 'To Eat', name: '#coolidge Jins' },
  { type: 'To Eat', name: '#coolidge Michael\'s Deli' },
  { type: 'To Eat', name: '#coolidge Otto Happy Hour 4-6p' },
  { type: 'To Eat', name: '#coolidge Pure Cold Press' },
  { type: 'To Eat', name: '#coolidge Seven Subs' },
  { type: 'To Eat', name: '#coolidge Shiki' },
  { type: 'To Eat', name: '#coolidge Vittorio Grill' },
  { type: 'To Eat', name: '#dessert #fenway Japonaise Bakery' },
  { type: 'To Eat', name: '#dessert #washingstonsquare Emack Bolios' },
  { type: 'To Eat', name: '#dessert #washingstonsquare Gelato At Athans' },
  { type: 'To Eat', name: '#fenway Gyu-kyu Bbq' },
  { type: 'To Eat', name: '#quincy Jnj Turo Turo - Filipino' },
  { type: 'To Eat', name: '#washingtonsquare Fairsted Kitchen' },
  { type: 'To Eat', name: '#washingtonsquare Sunny Boy' },
  { type: 'To Eat', name: 'Amsterdam Falafel Shop' },
  { type: 'To Eat', name: 'Aurum' },
  { type: 'To Eat', name: 'Baked Chimichangas' },
  { type: 'To Eat', name: 'Bbq Protein Of Choice W Cheddar And Caramelized Onions' },
  { type: 'To Eat', name: 'Beans On Baked Potato' },
  { type: 'To Eat', name: 'Beans On Toast' },
  { type: 'To Eat', name: 'Breakfast - Huevos Rancheros' },
  { type: 'To Eat', name: 'Breakfast - Parfait' },
  { type: 'To Eat', name: 'Bunny Pasta W Peas And Corn' },
  { type: 'To Eat', name: 'Chacarero Remake' },
  { type: 'To Eat', name: 'Cheese On Toast W Sardines' },
  { type: 'To Eat', name: 'Chicken With Mushroom Sauce' },
  { type: 'To Eat', name: 'Crab Salad Sandwich' },
  { type: 'To Eat', name: 'Creamy Clam Chowder' },
  { type: 'To Eat', name: 'Crispy Tortilla Salad Bowl' },
  { type: 'To Eat', name: 'Cuban Sandwich - Tofurky, Pickles, Cheese, Mustard, Toasted / Dessert - Black Bean Brownies' },
  { type: 'To Eat', name: 'Dessert - Black Bean Brownies' },
  { type: 'To Eat', name: 'Dessert - Chocolate' },
  { type: 'To Eat', name: 'Dessert - Clementines' },
  { type: 'To Eat', name: 'Dessert - Fruit' },
  { type: 'To Eat', name: 'Dessert - Jello' },
  { type: 'To Eat', name: 'Dessert - Mochi Ice Cream' },
  { type: 'To Eat', name: 'Dessert - Vanilla Ice Cream With Grapefruit' },
  { type: 'To Eat', name: 'Fattoush With Yogurt-tahini Dressing' },
  { type: 'To Eat', name: 'Financiers At Clear Flour Bread' },
  { type: 'To Eat', name: 'Fish Tacos' },
  { type: 'To Eat', name: 'Flatbread Pizza' },
  { type: 'To Eat', name: 'Fried Egg Pizza' },
  { type: 'To Eat', name: 'Fried Rice And Seafood Blend Wraps' },
  { type: 'To Eat', name: 'Grilled Cheese With Onions And Avocado' },
  { type: 'To Eat', name: 'Homemade Pho' },
  { type: 'To Eat', name: 'http://www.ambitiouskitchen.com/2014/04/healthy-flourless-black-bean-avocado-brownies-vegan-and-gluten-free/' },
  { type: 'To Eat', name: 'http://www.buzzfeed.com/rachelysanders/easy-weeknight-dinners#.wn1ojm65lv' },
  { type: 'To Eat', name: 'http://www.cooktj.com/by-category/4/recipe?term=entrees' },
  { type: 'To Eat', name: 'http://www.foodnetwork.com/recipes/alton-brown/sherried-sardine-toast-recipe' },
  { type: 'To Eat', name: 'Drunken-noodles-pad-kee-mao - http://www.gimmesomeoven.com/drunken-noodles-pad-kee-mao/' },
  { type: 'To Eat', name: 'Fattoush-salad - http://www.gimmesomeoven.com/fattoush-salad/' },
  { type: 'To Eat', name: 'Mushroom-bolognese - http://www.gimmesomeoven.com/mushroom-bolognese/' },
  { type: 'To Eat', name: 'Zesty-lentil-spinach-salad-recipe - http://www.gimmesomeoven.com/zesty-lentil-spinach-salad-recipe/' },
  { type: 'To Eat', name: 'http://www.hotforfoodblog.com/recipes/2015/8/20/asian-noodle-salad-with- Edamame-sweet-ginger-dressing' },
  { type: 'To Eat', name: 'http://www.lecremedelacrumb.com/creamy-honey-mustard-dressing/' },
  { type: 'To Eat', name: 'http://www.recipetineats.com/thai-stir-fried-noodles-pad-see-ew/' },
  { type: 'To Eat', name: 'https://www.google.com/amp/www.eatingwell.com/recipe/250926/ Fattoush-with-yogurt-tahini-dressing/amp/?client=safari' },
  { type: 'To Eat', name: 'https://www.sunbasket.com/recipe/hodo-soy-tofu-burgers-with-sweet-chile- Mayonnaise' },
  { type: 'To Eat', name: 'Korean Beef Bowl - http://damndelicious.net/2013/07/07/korean-beef-bowl/' },
  { type: 'To Eat', name: 'Lasagna' },
  { type: 'To Eat', name: 'Mashed Potato Pizza' },
  { type: 'To Eat', name: 'Miso Fish W Farro And Garlic Snap Peas' },
  { type: 'To Eat', name: 'Ninja Steamed Fish With Mash And Veg' },
  { type: 'To Eat', name: 'Omelette' },
  { type: 'To Eat', name: 'Pasta Salad With Veggies' },
  { type: 'To Eat', name: 'Pasta W Pesto Sauce' },
  { type: 'To Eat', name: 'Pasta W Red Sauce' },
  { type: 'To Eat', name: 'Pizza - http://www.ninjakitchen.com/recipes/search/0/all/100510/pizza-night' },
  { type: 'To Eat', name: '#somerville Poke Works' },
  { type: 'To Eat', name: 'Quiche' },
  { type: 'To Eat', name: 'Red Clam Chowder' },
  { type: 'To Eat', name: 'Roast Dinner - Main, Boiled Peas And Carrots, Roasted Potatoes, Cauliflower' },
  { type: 'To Eat', name: 'Roasted Spaghetti Squash' },
  { type: 'To Eat', name: 'Salmon - Baked' },
  { type: 'To Eat', name: 'Salmon - Crispy With Crab Crushed Potatoes' },
  { type: 'To Eat', name: 'Salmon-fish Salad On Toasted Bun' },
  { type: 'To Eat', name: 'Shakshuka' },
  { type: 'To Eat', name: 'Shepherd\'s Pie' },
  { type: 'To Eat', name: 'Smashed Avocado Toast' },
  { type: 'To Eat', name: 'Smashed Chick Pea Toast' },
  { type: 'To Eat', name: 'Smashed White Bean Toast' },
  { type: 'To Eat', name: 'Snack - Guacamole' },
  { type: 'To Eat', name: 'Snack - Kale Chips' },
  { type: 'To Eat', name: 'Snack - Mushroom Mochi' },
  { type: 'To Eat', name: 'Snack - Pizza Bites' },
  { type: 'To Eat', name: 'Snack - Seaweed Snacks' },
  { type: 'To Eat', name: 'Snack - Snap Peas' },
  { type: 'To Eat', name: 'Spaghetti On Toast' },
  { type: 'To Eat', name: 'Steamed Whole Fish' },
  { type: 'To Eat', name: 'Sweet Potato Chili' },
  { type: 'To Eat', name: 'Tacos W Veggie Meat Or Something' },
  { type: 'To Eat', name: 'Takeout - Bbq' },
  { type: 'To Eat', name: 'Takeout - Burgers' },
  { type: 'To Eat', name: 'Takeout - Burritos' },
  { type: 'To Eat', name: 'Takeout - Italian' },
  { type: 'To Eat', name: 'Takeout - Korean' },
  { type: 'To Eat', name: 'Takeout - Mediterranean' },
  { type: 'To Eat', name: 'Takeout - Pizza' },
  { type: 'To Eat', name: 'Takeout - Sandwiches' },
  { type: 'To Eat', name: 'Takeout - Sushi' },
  { type: 'To Eat', name: 'Takeout - Thai' },
  { type: 'To Eat', name: 'Takeout - Vietnamese' },
  { type: 'To Eat', name: 'Teriyaki Noodle Stir Fry With Crispy Tofu' },
  { type: 'To Eat', name: 'Thai' },
  { type: 'To Eat', name: 'These Look Good https://www.buzzfeed.com/marietelling/28-delicious-' },
  { type: 'To Eat', name: 'Things-to-cook-?utm_term=.ww5mm48vbl#.itnpp5yxnz' },
  { type: 'To Eat', name: 'Tomato And Onion Pizza' },
  { type: 'To Eat', name: 'Tomato Mozarella Basil' },
  { type: 'To Eat', name: 'Tomato Mozzarella Basil Quinoa Bake' },
  { type: 'To Eat', name: 'Trader Joe\'s Ravioli' },
  { type: 'To Eat', name: 'Try Japanese Curry' },
  { type: 'To Eat', name: 'Tuna Salad On Toast' },
  { type: 'To Eat', name: 'Vegan Cacio E Pepe http://www.kitchentreaty.com/vegan-cacio-e-pepe/' },
  { type: 'To Eat', name: 'Vegan Parmesan http://minimalistbaker.com/how-to-make-vegan-parmesan- Cheese/' },
  { type: 'To Eat', name: 'Veggie + Goat Cheese Quesadilla' },
  { type: 'To Eat', name: '#brookline Wow Bbq' },
  { type: 'To Eat', name: 'Yellow Curry With Tofu' }
];
